### ISSUE TITLE
Last seen timer includes shorts

### ISSUE THREAD

**Issue by Stanliestt** [iSneeze/IMissYuko#2]
The website pulls the most recently published video, which includes shorts.
> Last seen: Xd XXh XXm XXs ago streaming

Potential solutions include simply removing the word "streaming"

or

Updating the Holodex API call to only include videos of type stream
[Link to API documentation](https://docs.holodex.net/docs/holodex/ba328f7332280-query-videos#:~:text=singing-,type,clip,-from)

**Comment by iSneeze** [comment]
Yeah problem is the holodex api still has `"type": "stream"` for shorts, so I cant really filter it D: but I'll look into it

**Comment by iSneeze** [comment]
little late update but I fixed it 2 weeks ago :D
